env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/essential
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 13
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
  - prettier
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  prettier/prettier:
    - error
    # - arrowParens: 'avoid'
    #   bracketSameLine: false
    #   bracketSpacing: true
    #   embeddedLanguageFormatting: auto
    #   htmlWhitespaceSensitivity: css
    #   insertPragma: false
    #   jsxSingleQuote: true
    #   proseWrap: preserve
    #   quoteProps: as-needed
    #   requirePragma: false
    #   semi: false
    #   singleQuote: true
    #   tabWidth: 2
    #   trailingComma: es5
    #   useTabs: false
    #   printWidth: 80
