// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCardPanel: typeof import('element-plus/es')['ElCardPanel']
    ElCards: typeof import('element-plus/es')['ElCards']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}

export {}
